// <auto-generated />
using System;
using Lageros.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Lageros.Migrations
{
    [DbContext(typeof(LagerosContext))]
    [Migration("20210124000308_NabavaTable")]
    partial class NabavaTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("Lageros.Models.NabavaTonera", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("DatumZamjene")
                        .HasColumnType("datetime2");

                    b.Property<int>("TonerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TonerId");

                    b.ToTable("NabavaTonera");
                });

            modelBuilder.Entity("Lageros.Models.Printer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("IP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naziv")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Printeri");
                });

            modelBuilder.Entity("Lageros.Models.Toner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Kolicina")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Toner");
                });

            modelBuilder.Entity("Lageros.Models.ZamjenaToner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("DatumZamjene")
                        .HasColumnType("datetime2");

                    b.Property<int>("PrinterId")
                        .HasColumnType("int");

                    b.Property<int>("TonerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PrinterId");

                    b.HasIndex("TonerId");

                    b.ToTable("ZamjenaToner");
                });

            modelBuilder.Entity("Lageros.Models.NabavaTonera", b =>
                {
                    b.HasOne("Lageros.Models.Toner", "Toner")
                        .WithMany()
                        .HasForeignKey("TonerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Toner");
                });

            modelBuilder.Entity("Lageros.Models.ZamjenaToner", b =>
                {
                    b.HasOne("Lageros.Models.Printer", "Printer")
                        .WithMany()
                        .HasForeignKey("PrinterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lageros.Models.Toner", "Toner")
                        .WithMany()
                        .HasForeignKey("TonerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Printer");

                    b.Navigation("Toner");
                });
#pragma warning restore 612, 618
        }
    }
}
